services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - "5000:5000" # backend ASP.NET
    depends_on:
      - mongo

  simulator:
    image: node:18
    working_dir: /workspace/Simulador/proyecto
    volumes:
      - .:/workspace:cached
    command: npm run dev
    ports:
      - "3000:3000" # simulador Node.js
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
